[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ngeodesic"
version = "0.0.2a1"
description = "Geometry-First AI Reasoning Engine"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"                 # modern SPDX string
authors = [{ name = "Ian C. Moore" }]
dependencies = ["numpy>=1.26", "typing_extensions>=4.8"]
license-files = ["LICENSE", "NOTICE*"] # replaces old tool.setuptools.license-files

[project.optional-dependencies]
ml = ["scikit-learn>=1.4"]
viz = ["matplotlib>=3.8", "scipy>=1.11"]
dev = ["pytest>=8", "pytest-cov>=5", "ruff>=0.5", "mypy>=1.10"]

[tool.setuptools]
package-dir = { "" = "python" }       # 👈 your code is under python/

[project.scripts]
ngeodesic-stage11-demo = "ngeodesic.test.stage11.run_benchmark:main"

[tool.setuptools.packages.find]
where = ["python"]
include = ["ngeodesic*"]
